/*
  # Add session_group_id to sessions table

  1. Modified Tables
    - `sessions`
      - Added `session_group_id` (uuid, nullable) to link work and break sessions
        that belong to the same study round

  2. Indexes
    - Added composite index on (user_id, session_group_id) for efficient
      group-based queries in the history page

  3. Notes
    - Existing sessions will have NULL session_group_id and will be grouped
      using proximity-based matching on the client side
    - New sessions will receive a group ID generated by the frontend
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'sessions' AND column_name = 'session_group_id'
  ) THEN
    ALTER TABLE sessions ADD COLUMN session_group_id uuid;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sessions_user_group
  ON sessions(user_id, session_group_id);
